// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/purchase.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_proto_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *PurchaseRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PurchaseRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_proto_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PurchaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerRequest) Reset() {
	*x = CustomerRequest{}
	mi := &file_proto_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRequest) ProtoMessage() {}

func (x *CustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRequest.ProtoReflect.Descriptor instead.
func (*CustomerRequest) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *CustomerRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type Purchase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_proto_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *Purchase) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Purchase) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Purchase) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type PurchaseList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*Purchase            `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseList) Reset() {
	*x = PurchaseList{}
	mi := &file_proto_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseList) ProtoMessage() {}

func (x *PurchaseList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseList.ProtoReflect.Descriptor instead.
func (*PurchaseList) Descriptor() ([]byte, []int) {
	return file_proto_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseList) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

var File_proto_purchase_proto protoreflect.FileDescriptor

const file_proto_purchase_proto_rawDesc = "" +
	"\n" +
	"\x14proto/purchase.proto\x12\bpurchase\"i\n" +
	"\x0fPurchaseRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\"D\n" +
	"\x10PurchaseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"2\n" +
	"\x0fCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"U\n" +
	"\bPurchase\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"@\n" +
	"\fPurchaseList\x120\n" +
	"\tpurchases\x18\x01 \x03(\v2\x12.purchase.PurchaseR\tpurchases2\x9a\x01\n" +
	"\x0fPurchaseService\x12D\n" +
	"\vAddPurchase\x12\x19.purchase.PurchaseRequest\x1a\x1a.purchase.PurchaseResponse\x12A\n" +
	"\fGetPurchases\x12\x19.purchase.CustomerRequest\x1a\x16.purchase.PurchaseListB%Z#github.com/atri/go-grpc-purchase/pbb\x06proto3"

var (
	file_proto_purchase_proto_rawDescOnce sync.Once
	file_proto_purchase_proto_rawDescData []byte
)

func file_proto_purchase_proto_rawDescGZIP() []byte {
	file_proto_purchase_proto_rawDescOnce.Do(func() {
		file_proto_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)))
	})
	return file_proto_purchase_proto_rawDescData
}

var file_proto_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_purchase_proto_goTypes = []any{
	(*PurchaseRequest)(nil),  // 0: purchase.PurchaseRequest
	(*PurchaseResponse)(nil), // 1: purchase.PurchaseResponse
	(*CustomerRequest)(nil),  // 2: purchase.CustomerRequest
	(*Purchase)(nil),         // 3: purchase.Purchase
	(*PurchaseList)(nil),     // 4: purchase.PurchaseList
}
var file_proto_purchase_proto_depIdxs = []int32{
	3, // 0: purchase.PurchaseList.purchases:type_name -> purchase.Purchase
	0, // 1: purchase.PurchaseService.AddPurchase:input_type -> purchase.PurchaseRequest
	2, // 2: purchase.PurchaseService.GetPurchases:input_type -> purchase.CustomerRequest
	1, // 3: purchase.PurchaseService.AddPurchase:output_type -> purchase.PurchaseResponse
	4, // 4: purchase.PurchaseService.GetPurchases:output_type -> purchase.PurchaseList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_purchase_proto_init() }
func file_proto_purchase_proto_init() {
	if File_proto_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_purchase_proto_rawDesc), len(file_proto_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_purchase_proto_goTypes,
		DependencyIndexes: file_proto_purchase_proto_depIdxs,
		MessageInfos:      file_proto_purchase_proto_msgTypes,
	}.Build()
	File_proto_purchase_proto = out.File
	file_proto_purchase_proto_goTypes = nil
	file_proto_purchase_proto_depIdxs = nil
}
